### ISSUE TITLE
Nested SubSchema array has "Generic" type

### ISSUE THREAD

**Issue by Thammada** [nodkz/graphql-compose-mongoose#13]
This is similar to issue #2, but even when I use mongoose.Schema the resulting field still has "Generic" type

I can replicate this using the example from README.md
```
const mongoose = require('mongoose')
const { composeWithMongoose } = require('graphql-compose-mongoose')
const { GQC } = require('graphql-compose')

const LanguagesSchema = new mongoose.Schema({
  language: String
});

const UserSchema = new mongoose.Schema({
  name: String,
  languages: {
    type: [LanguagesSchema],
    default: [],
  }
});
const UserModel = mongoose.model('UserModel', UserSchema);
const UserTC = composeWithMongoose(UserModel);

UserTC.get('languages') // Generic
```

I'm using the following versions
```
    "graphql-compose": "^1.8.0",
    "graphql-compose-connection": "^2.1.2",
    "graphql-compose-mongoose": "^1.4.2",
    "mongoose": "^4.7.4",
```

**Comment by Thammada** [comment]
Looks like this is related to #14 
I followed @yoadsn advice https://github.com/nodkz/graphql-compose-mongoose/issues/14#issuecomment-269219596 and it's resolved now.

**Comment by nodkz** [comment]
Sorry for an inconvenience and delayed response.

The problem was with my Travis CI configs and publishing setup (it put peerDependencies to the package dependencies). 

Please upgrade to latest `graphql-compose@1.8.1` and `graphql-compose-mongoose@1.4.5`.
It should work properly.
