### ISSUE TITLE
deleteById and findByIdAndRemove

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose-mongoose#17]
Ref: https://github.com/nodkz/graphql-compose-mongoose/blob/dda449ed6d4bd6ea1d2aca7887388cc4a9bab871/src/resolvers/removeById.js#L76

I think that using `findByIdAndRemove` is not the correct way of doing it.
it is alot cleaner if you are doing `find()` and then `.delete()`

Using `findByIdAndRemove` is a force delete that is not possible to override with plugins and functions.
Or am i wrong? 😄 
https://github.com/dsanel/mongoose-delete/issues/13#issuecomment-234715856

**Comment by nodkz** [comment]
Good catch. Maybe you create PR?
Myself I can do this not before next week.

**Comment by stoffern** [comment]
I will create a PR for it, no worries :)

**Comment by nodkz** [comment]
Thanks! 

Don't forget change both `removeById` and `removeOne` (as example you may see `updateById`).

**Comment by stoffern** [comment]
My bad actually, the `delete()` is a function supplied by the mongoose soft delete function, and the `remove()` and `findByIdAndRemove` is the correct ways to do it occourding to mongodb docs.

In order to use the delete function for that plugin its better to create a custom resolver 😉 

Closing this issue.
