### ISSUE TITLE
_id is stripped from embedded documents

### ISSUE THREAD

**Issue by theJoeBiz** [nodkz/graphql-compose-mongoose#19]
This issue was driving me mad, so I followed the source code only to find that this is by design.

The _id is removed during the conversion from model to graphql ([#L306](https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/fieldsConverter.js#L306) and [#L351](https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/fieldsConverter.js#L351)).

I want to write a query like this:

```graphql
query {
  accounts {
    _id
    name
    websites {
    	_id
      domain
      description
    }
  }
}
```

My front-end relies on the _id field of the embedded website documents, so I'm a bit confused what the purpose of removing them is.

Here is my Account schema:

```javascript
const WebsiteSchema = new Schema({
  domain: String,
  description: String
});

const AccountSchema = new Schema({
  name: String,
  createdAt: Date,
  updatedAt: Date,
  deletedAt: Date,
  ...
  websites: [WebsiteSchema]
});
```

**Comment by nodkz** [comment]
Removed for purity. And maybe was some problem with them in past, I don't remember. But now I do not see any problem if it will be allowed.

Let try to return them under some option provided to converter. Can you open PR?
