### ISSUE TITLE
schema for nest model

### ISSUE THREAD

**Issue by jackypan1989** [nodkz/graphql-compose-mongoose#3]
I have a user <-> company relation
so I build like that
```
const UserSchema = new mongoose.Schema({
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company'
  }
})
```
after adding relation, it works with RootQuery.

However, it failed when I try to RootMutation user with companyId.
The graphql console shows that company is "GQLReference" not MongoID or String type
till I wrote 
```
const UserSchema = new mongoose.Schema({
  company: {
    type: String,
  }
})
```
to make RootQuery and RootMutation available.

Did I miss anything?

**Comment by nodkz** [comment]
Auto resolving of Mongoose Relations not implemented. And I not decided yet should it works by default or not. Cause think that mongoose models should be explicitly converted.

Anyway I'll fix your problem tomorrow. Out of work today.
Graphql-compose-Mongoose should create proper type for fields in mutations.

To solve your problem right now, just change type for input field
```js
UserTC.get('$updateOne.@record).addField('companyId', { type: 'String' });
// The same but longer
const updateOneResolver = UserTC.getResolver('updateOne');
const argumentRecordITC = new InputTypeComposer(updateOneResolver.getArg('record'));
argumentRecordITC.addField('companyId', { type: 'String' });
```

**Comment by jackypan1989** [comment]
Thank you @nodkz. I guess it would be great if we could handle String <-> MongoId in the middle layer. Especially we may need to use "type: mongoose.Schema.Types.ObjectId" with traditional rest API endpoint .

**Comment by nodkz** [comment]
Mongoose converts proper mongoid provided as string to MongoID object if field has `mongoose.Schema.Types.ObjectId` type. [Proof](https://graphql-compose.herokuapp.com/user/?query=%0A%7B%0A%20%20userById(_id%3A%20%2257bb44dd21d2befb7ca3f010%22)%20%7B%0A%20%20%20%20_id%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20).
