### ISSUE TITLE
[Relay Modern] warnings

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose-mongoose#30]
Using custom ScalarTypes is not supported in `Relay Modern`
look here:
https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/flowtype/printFlowTypes.js#L286-L318

@nodkz Should this be fixed here or on the Relay Modern?
I guess the last option would be most correct 😕

**Comment by nodkz** [comment]
Looking at the code, I can say that they **are supported**. Custom ScalarTypes will have `any` flow annotation and it is correct behavior.

All that need just has the ability in Relay to disable warnings for all ScalarTypes:
```js
        console.warn(
          `Could not convert GraphQLScalarType(${type.name}), using 'any'`,
        );
```
Or maybe better create some customizable list via `relay-compiler` options which will provide annotations.

**Comment by stoffern** [comment]
Closing this one as it it a relay issue and not `graphql-compose-mongoose`
