### ISSUE TITLE
graphql 0.10.0 breaking changes

### ISSUE THREAD

**Issue by Anthonyzou** [nodkz/graphql-compose-mongoose#31]
This update seem to break the type resolution. I'm not sure if this is a `graphql-compose` issue.

```
GQC: can not convert field 'UserModelName.first' to InputType
      It should be GraphQLObjectType, but got 
      String
GQC: can not convert field 'UserModel.email' to InputType
      It should be GraphQLObjectType, but got 
      String
```

**Comment by nodkz** [comment]
Try to remove `node_modules` and install packages from scratch.
You probably have duplicate installed versions of graphql-js.

Reopen if problem stays.
