### ISSUE TITLE
Resolver Connection with multiple DBs

### ISSUE THREAD

**Issue by Anthonyzou** [nodkz/graphql-compose-mongoose#32]
Hi I seem to have an issue with mutiple calls to the connection resolver and findMany resolver. 
I have an example repo here [https://github.com/Anthonyzou/compose-mongoose-multitenant](https://github.com/Anthonyzou/compose-mongoose-multitenant)

The error that I get is: 
`Error: Schema must contain unique named types but contains multiple types named "FilterFindManyMessageModelInput".`

commenting out 
`getResolver('findMany')`
or
`getResolver('connection')`
fixes the issue.

**Comment by nodkz** [comment]
Oh, I see that you use multiple DBS/models. Try to clear `mongooseTypeStorage` before each schema build.

```diff
- import { composeWithMongoose, GraphQLMongoID, filterHelperArgs } from 'graphql-compose-mongoose';
+ import { composeWithMongoose, GraphQLMongoID, filterHelperArgs, mongooseTypeStorage } from 'graphql-compose-mongoose';

...
const MessageModel = db.model('MessageModel', MessageSchema);

+ mongooseTypeStorage.clear();
const MessageTC = composeWithMongoose(MessageModel, {});
...
```

**Comment by Anthonyzou** [comment]
Yes wow, thanks! That works!

Thanks a lot of the help!

You should consider a donation method. This is a really nice library!
