### ISSUE TITLE
Need a clear example for using subscriptions

### ISSUE THREAD

**Issue by atteia** [nodkz/graphql-compose-mongoose#44]
Hello,
I hope to get a clear example to add subscriptions 
I read this #https://github.com/nodkz/graphql-compose/issues/60  but it's not clear enough

I use your libs with relay  
graphql-compose 
graphql-compose-connection 
graphql-compose-mongoose 
graphql-compose-relay 

best regards,

**Comment by nodkz** [comment]
@atteia sorry I do not have a clear example.

Close this issue, let continue discussion in https://github.com/nodkz/graphql-compose/issues/60
Thnx
