### ISSUE TITLE
Old good pagination

### ISSUE THREAD

**Issue by akaNightmare** [nodkz/graphql-compose-mongoose#46]
Hello,

I want to use pagination (`{ totalCount: Number, currentPage: Number, itemsPerPage: Number, totalPages: Number }`). Is it possible to add that?

Thanks.

**Comment by nodkz** [comment]
@akaNightmare great feature request!
Needs to write standard resolver. 
Are variable names (`{ totalCount: Number, currentPage: Number, itemsPerPage: Number, totalPages: Number }`) from some framework, or it just your proposed variant of names? In other words, can I choose other names for implementation?

**Comment by nodkz** [comment]
Something like this:
```js
export type PaginationType = {
  count: number,
  items: any[],
  pageInfo: PageInfoType,
};

export type PageInfoType = {
  page: number,
  perPage: number,
  totalPages: number,
  hasPreviousPage: boolean,
  hasNextPage: boolean,
};
```

**Comment by akaNightmare** [comment]
@nodkz 

> from some framework, or it just your proposed variant of names? In other words, can I choose other names for implementation?

It's just an example. Sure, you can choose other names.
```js
export type PaginationType = {
  count: number,
  items: any[],
  pageInfo: PageInfoType,
};

export type PageInfoType = {
  page: number,
  perPage: number,
  totalPages: number,
  hasPreviousPage: boolean,
  hasNextPage: boolean,
};
```
IMHO: it's not quiet ok, I think all paging info should be in one place:
```js
export type PaginationType = {
  edges: any[],
  pageInfo: PageInfoType,
};

export type PageInfoType = {
  totalCount: number,  
  currentPage: number,
  perPage: number,
  pageCount: number,
  hasPreviousPage: boolean,
  hasNextPage: boolean,
};
```

**Comment by nodkz** [comment]
Implemented via new plugin [graphql-compose-pagination](https://github.com/nodkz/graphql-compose-pagination).

It was added to graphql-compose-mongoose in v 1.7.0. Update to this version and add `graphql-compose-pagination to your dependencies in package.json.

Live demo avaliable [here](http://graphql-compose.herokuapp.com/user/?query=%0A%7B%0A%20%20userPagination(perPage%3A%203%2C%20page%3A%202%2C%20sort%3A%20_ID_ASC)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20gender%0A%20%20%20%20%20%20age%0A%20%20%20%20%7D%0A%20%20%20%20count%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20currentPage%0A%20%20%20%20%20%20perPage%0A%20%20%20%20%20%20itemCount%0A%20%20%20%20%20%20pageCount%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)

----

I decide to make such types:
```js
export type PaginationType = {
  items: any[], // avoid misunderstanding, in connection field `edges` is an array of Object({ node, cursor }) but here we want to keep array of nodes. So `edges` is not a good name. 
  pageInfo: PageInfoType,
  count: number, // keep it for compatibility with `connection` resolver shape.
};

export type PageInfoType = {
  currentPage: number,
  perPage: number,
  itemCount: number, // same value `PageInfoType.count` 
  pageCount: number,
  hasPreviousPage: boolean,
  hasNextPage: boolean,
};
```

So item number can be obtained in two ways via `PaginationType.count` or via `PaginationType.PageInfoType.itemCount`.

Please try it. 
If you have some additions or found an error, let me know ASAP.

**Comment by akaNightmare** [comment]
@nodkz thanks =)
