### ISSUE TITLE
How to add a relation in a structured object ?

### ISSUE THREAD

**Issue by whirly** [nodkz/graphql-compose-mongoose#49]
I've got a mongoose schema where the data are a bit more structured than usual :

```js
const FixtureSchema = new Schema({
    day: { type: Number },
    idMpg: { type: String },
    home: {
        team: { type: Schema.Types.ObjectId, ref: "Team" },
        formation: { type: String },
        performances: [ { type: Schema.Types.ObjectId, ref: "Performance" }]
    },
    away: {
        team: { type: Schema.Types.ObjectId, ref: "Team" },
        formation: { type: String },
        performances: [ { type: Schema.Types.ObjectId, ref: "Performance" }]
    }
});
```

I tried to add a relation on home.team and away.team but I can do that as when I call the addRelation it complains about the dot. I could easily destructure the object replacing home.team by home_team and so on, but it would be a bit ugly. So what could I do to add my relation ?

Thanks,
Stéphane

**Comment by nodkz** [comment]
Install latest `graphql-compose@2.3.0` I added new [methods](https://github.com/nodkz/graphql-compose/releases/tag/v2.3.0).

So your code should look something like this:
```js
const Fixture = mongoose.model('Fixture', FixtureSchema);
const FixtureTC = composeWithMongoose(Fixture);

const FixtureHomeTC = FixtureTC.getFieldTC('home');
FixtureHomeTC.addRelation('teamObj', {
  resolver: () => TeamTC.getResolver('findById'),
  prepareArgs: {
    _id: source => source.team,
  },
  projection: { team: 1 },
});
```

**Comment by whirly** [comment]
Works like a charm !
