### ISSUE TITLE
Insert JSON in mutation from server code

### ISSUE THREAD

**Issue by nicholasareed** [nodkz/graphql-compose-mongoose#58]
I have a simple model with a single JSON field. 

```
const UserSchema = new mongoose.Schema({
  profile: mongoose.Schema.Types.Mixed,
});
const UserModel = mongoose.model('users', UserSchema);
const UserTC = composeWithMongoose(UserModel);
...mutation methods left out 
```

How do I insert JSON into that field using a server-side query? 

```
let profile = {test: "profile"}
let mutationQuery_NewUser = `
  mutation {
    userCreate(record:{
      profile: ${profile},
    }) {
      recordId
    }
  }
`
graphql.graphql(mySchema, mutationQuery_NewUser)
```

This does not work ([Object object] tries to get inserted), and neither does replacing with a JSON.stringified value, or anything else I could think of. 

Is it possible to cast the JSON scalar to something else for input?

**Comment by nodkz** [comment]
JSON type as input should work perfectly.
Try to use graphql `variables`: http://graphql.org/learn/queries/#variables. 

And pass them in following manner:
```js
const res = await graphql.graphql({
  schema: mySchema,
  source: mutationQuery_NewUser,
  variableValues: { profile },
});

console.log(res);
```
