### ISSUE TITLE
How to create custom resolvers?

### ISSUE THREAD

**Issue by danielmahon** [nodkz/graphql-compose-mongoose#6]
Hey @nodkz, first of all, great stuff. Just switched over from https://github.com/RisingStack/graffiti-mongoose. Secondly, how do you suggest adding a new resolver? For example, if I want to add a custom mutation or RPC. Didn't know if there was a better way then to copy an existing resolver... Thanks!

**Comment by danielmahon** [comment]
Nevermind, I was able to accomplish by using `wrapResolve`. I am working on mapping all schema methods to GraphQL mutation types.
```javascript
    // Define methods
    _.each(list.model.schema.methods, (method, methodName) => {
      // modelMethodName: run method function
      mutations[name + utils.upcase(methodName)] = types[key]
        .getResolver('findById')
        .wrapResolve(() => ({ args = {} }) => {
          // console.log(source, args, context);
          if (args._id) {
            const query = model.findById(args._id);
            // Populate fields
            query.populate(_.map(list.relationshipFields, 'path').join(' '));
            return query.exec().then(doc => new Promise((resolve, reject) => {
              doc[methodName]((error, newDoc) => {
                if (error) return reject(error);
                return resolve(newDoc);
              });
            }));
          }
          return Promise.resolve(null);
        });
    });
```

**Comment by nodkz** [comment]
Crazy stuff 👍
Also if you want to save new resolver in type for further using may do following:
```js
ModelTC.setResolver('youMethod', ModelTC.get('$findById').wrapResolve(...));
```

**Comment by yoadsn** [comment]
@danielmahon Can you explain why are you doing it? I thought the mutations I can get from graphql-compose-mongoose would do the job. What am I missing?

**Comment by danielmahon** [comment]
@yoadsn Sure thing. First, let me explain that I'm pretty new to GraphQL so I may/probably be going about certain things wrong. Also, I'm using KeystoneJS as a backend which more or less defines my mongoose schemes. My thought for hooking up the schema methods is that while the default CRUD types work great for modifying database data they don't seem to be a intuitive solution for RPCs. For example it makes more sense to me to run a 'sendNotifications' method attached to a schema and have it potentially but not necessarily modify a document then to update the document and watch the field for changes then run the method. So in this case I might map 'userSendNotifications' mutation to the 'sendNotifications' schema method which can be invoked on a certain record by wrapping the 'findById' resolver. That's the thought anyways. I'm open to suggestions! Eventually it may also be nice to make a compose plugin for keystone.

**Comment by yoadsn** [comment]
@danielmahon I think I understood - I'm not familiar with the inner workings of KeystoneJS so maybe in that scemario it makes sense. I never thought of GraphQL as an RPC api, but more as a client integration API. if it makes sense, the two have different semantics in my mind.
Thanks for opening my eyes for that possibility.

**Comment by danielmahon** [comment]
Let me ask you this: if you built a notepad app that allowed a user to create a note and then email that note to a friend how would you normally handle telling the server to send that  email through a GraphQL only API? This is where I'm not entirely sure of the "proper" way to handle it. In a REST API I would of just created an endpoint for that purpose.

**Comment by yoadsn** [comment]
Well, maybe on a larger context I would be giving a different answer but for an async. in nature operation such as sending something over - the semantics would involve those entities among others:
SendRequest { origin, destination, content }
SendRequestState { sendRequest, status, timestamp }

And so GQL API would expose a mutation to "post/cancel/retry SendRequests" and to "Query SendRequestStatuse(s)".
SendRequest would have a connection to SendRequestStatuses, and a reference to the "latest status". (assuming retries, cancellations are possible and tracked).

So you see, I imagine the philosophy behind GQL is that, well, all is a graph, and everything in it are nodes and edges of that graph. In a way you could model any system with that paradigm and limiting the scope of "mutations" and "queries" to data stores may do some injustice to it.

Hope I'm not too "out there" :)
