### ISSUE TITLE
Connection in relation

### ISSUE THREAD

**Issue by jimzer** [nodkz/graphql-compose-mongoose#68]
Hello, first of all thank you for the good work. The graphql-comopose libraries are amazing and make life really easier ! 
I just have a question about making connection on a relation field.
Imagine I have User and Post schemas. A User has afield posts with the id of its posts.
How could I have a connection from the array of ids of the field posts in a relation. I mean something like this:

```
UserTC.addRelation(
  'friends',
  () => ({
    resolver: postTC.getResolver('connection'), // But I would like this connection to be from the array of id 
                                                                              contained in the field posts
    args: {
      _ids: (source) => source.posts,
    },
    projection: { posts: 1 }, // point fields in source object, which should be fetched from DB
  })
);
```
If you could help me doing this using your libraries it would be awesome !
Thanks in advance

**Comment by nodkz** [comment]
You are using old API. Let's [migrate](https://github.com/nodkz/graphql-compose/releases/tag/2.0.0) on new 2.0.0 API:
```js
UserTC.addRelation( 'friends', {
  resolver: () => PostTC.getResolver('findByIds'),
  prepareArgs: {
    _ids: (source) => source.posts,
  },
  projection: { posts: 1 },
});
```

For making relations via resolvers you just need to see its arguments via graphiql, and understood which args you should provide to them. 

You may do it here https://graphql-compose.herokuapp.com/user/ see DOCS in right panel for `query`
<img width="472" alt="screen shot 2017-09-25 at 16 50 12" src="https://user-images.githubusercontent.com/1946920/30805096-caf69b88-a211-11e7-9101-6ed345bf5b9c.png">


So for `connection`  you should prepare `filter` argument in such way:
```js
UserTC.addRelation( 'friends', {
  resolver: () => PostTC.getResolver('connection'),
  prepareArgs: {
    filter: (source) => ({ _ids: source.posts }),
  },
  projection: { posts: 1 },
});
```

**Comment by jimzer** [comment]
Thank you a lot. 
It works perfectly !
