### ISSUE TITLE
Avoid request to get only _id in relationship

### ISSUE THREAD

**Issue by fklingler** [nodkz/graphql-compose-mongoose#69]
Hello,

I have these models:

```
Proposal {
  offer: Offer
}
Offer {
  acceptedProposal: Proposal
}
```

I'd like to make a graphql request to get many `Offer`s,  and check if they have an `acceptedProposal` or not.
For that, I can do this:
```
query {
  offers {
    acceptedProposal {
      _id
    }
  }
}
```

But this will make a request for each offer *with* an acceptedProposal, to get the `_id`. Even though we already have the `acceptedProposal`'s `_id` in `Offer`.
Is there an easy way to avoid these requests? For now I simply declared the relation like this:

```
tc.addRelation('acceptedProposal', {
    resolver: () => proposalType.getResolver('findById'),
    prepareArgs: { _id: (source: IOfferDocument) => source.acceptedProposal },
    projection: { acceptedProposal: true }
});
```

I know I could create a new field like `acceptedProposalId` which will return the id directly (or the inverse, rename the relation so that I still can get the id with `acceptedProposal`), but I'd like to avoid to complexify the API.
Maybe we could allow the relation field to be of composed type `MongoId | Proposal` in some way, so it can handle nicely this case where we don't want any `Proposal` field?

Thanks a lot for your awesome graphql-compose packages :)

**Comment by nodkz** [comment]
Just add new custom field `hasProposal`, which will check presence of id in `acceptedProposal` and return `boolean` without requesting `Proposal` collection.

```js
tc.addFields({
  hasProposal: {
     type: 'Boolean',
     resolve: (source) => !!source.acceptedProposal,
     projection: { acceptedProposal: true },
  },
});
```

And you can do such query:
```
query {
  offers {
    hasProposal
  }
}
```

**Comment by fklingler** [comment]
Ok thanks, I was thinking about a more automatic approach but I guess it would cause many problems with the types in GraphQL!
