### ISSUE TITLE
latest release breaks the server. 

### ISSUE THREAD

**Issue by smooJitter** [nodkz/graphql-compose-mongoose#73]
```
/Users/ddcole/_dev/servers/jitter-party-server2/node_modules/graphql-compose-mongoose/lib/fieldsConverter.js:206

function convertFieldToGraphQL(field, prefix = '') {

SyntaxError: Unexpected token =

```

**Comment by nodkz** [comment]
What version of node do you use?
In last release i set up node 6 as minimal version.

**Comment by smooJitter** [comment]
looks like a problem with a the pagination package.

**Comment by smooJitter** [comment]
Using node 8.8

**Comment by nodkz** [comment]
Just published new versions with the support of Node v4. It's still in LTS. Till Apr, 2018.
My mistake was to update packages without following to semantic versioning. Sorry for this.

**Comment by nodkz** [comment]
Very strange that you get this error on Node 8.8.
Case by your error log it look like problem with `default function parameters`, but by KANGAX it has full support from version 6.5: https://kangax.github.io/compat-table/es6/#test-default_function_parameters

Anyway I'll keep node 4 code several months, then bump MAJOR version. But I do not know set 6 min version or migrate on node 8 right away? Or I think it will be better to provide several builds in one package for different node versions 4, 6, 8. By default, import provide the lowest version. And who wants to avoid run transpilled slow downed code, may switch on fresh builds, something like this 
```
import composeWithMongoose from 'graphq-compose-mongoose'; // node v4
import composeWithMongoose from 'graphq-compose-mongoose/node4'; // node v4
import composeWithMongoose from 'graphq-compose-mongoose/node6'; // node v6
import composeWithMongoose from 'graphq-compose-mongoose/node8'; // node v8
```

**Comment by smooJitter** [comment]
It's all good now!

**Comment by nodkz** [comment]
Great! Thanks for reporting!
