### ISSUE TITLE
Do not call mongoose for findByIds with empty array argument

### ISSUE THREAD

**Issue by croeck** [nodkz/graphql-compose-mongoose#74]
Hi,

I would assume, each call to the `findByIds` resolver with an empty array argument behaves just as if you pass no Array at all, it will always return the empty array `[]`. If this assumptions holds true, we could add a new check to line 49 in the referred example, so we do not have to call mongoose. 

https://github.com/nodkz/graphql-compose-mongoose/blob/4a854d2a44252d94d656b3b56ac2e2f47a44b71a/src/resolvers/findByIds.js#L46-L51

Any thoughts, objections?

Kind regards
Cedric

**Comment by nodkz** [comment]
Good catch!
Can you open PR with adding check for array with 0 length?
