### ISSUE TITLE
Relations and connections

### ISSUE THREAD

**Issue by gHashTag** [nodkz/graphql-compose-mongoose#76]
Relations and connections  

Created a Tweet model and installed a single link with User
```javascript
import mongoose from 'mongoose'
import { UserTC } from './user'
import composeWithMongoose from 'graphql-compose-mongoose'
	

const TweetSchema = new mongoose.Schema({
	  text: String,
	  userId: {
	    type: mongoose.Schema.Types.ObjectId,
	    ref: 'User'
          }
}, { timestamps: true } )
	

export const Tweet = mongoose.model('Tweet', TweetSchema)
export const TweetTC = composeWithMongoose(Tweet)
	
TweetTC.addRelation(
	  'user',
	  {
	    resolver: () => UserTC.getResolver('findById'),
	    prepareArgs: {
	      _id: source => source.userId
	    },
	    projection: { userId: true },
	  }
)
```

Created a User model and installed a multiple link with Tweet

```javascript
import mongoose from 'mongoose'
import { TweetTC } from './tweet'
import composeWithMongoose from 'graphql-compose-mongoose'
	
const UserSchema = new mongoose.Schema({
    username: {
	    type: String,
	    unique: true
	  },
	  firstName: String,
	  lastName: String,
	  avatar: String,
	  password: String,
	  email: String,
	  tweetsIds: [{
	    type: mongoose.Schema.Types.ObjectId,
	    ref: 'Tweet'
	  }],
}, { timestamps: true })

export const User = mongoose.model('User', UserSchema)
export const UserTC = composeWithMongoose(User)

UserTC.addRelation(
	  'tweets',
	  {
	    resolver: () => TweetTC.getResolver('findByIds'),
	    prepareArgs: {
	      _ids: (source) => source.tweetsIds || [],
	    },
	    projection: { tweetsIds: true },
	  }
)
```

  I create a mutation where in the userId field I pass the users id

```javascript
mutation {
  tweetCreate(record: {
    text: "Get tweet"
    userId: "5a0b3cde2c6afb534933fc5b"
  }) {
    recordId
  } 
}
```

As a result, the tweet was created

```javascript
{
  "_id": ObjectId("5a0b47fcb4f0015a0d59b6d6"),
  "text": "Get tweet",
  "userId": ObjectId("5a0b3cde2c6afb534933fc5b"),
}
```
, but the array with the user's field tweetsIds is empty

``` json 
 {
    "_id": "5a0b3cde2c6afb534933fc5b",
    "username": "sun",
    "tweetsIds": [],
},
```

The whole project lies [here](https://github.com/gHashTag/test-graphql-server/tree/graphql-compose-mongoose  )

Where am I mistaken?

**Comment by nodkz** [comment]
Yep, `tweetsIds` should be empty. graphql-compose-mongoose does not change related models. It may bring complexity to the codebase and bring unexpected behavior. Right now I do not serve `ref`, but maybe it would be changed in future.

For now, in your case you may create a custom mutation:
```js
TweetTC.addResolver({
  kind: 'mutation',
  name: 'createTweetWithRels',
  type: TweetTC.getResolver('createOne').getType(),
  args: TweetTC.getResolver('createOne').getArgs(),
  resolve: (rp) => {
     ...custom logic
     return $shapeOfOutputType;
  },
});
```
And then use this `createTweetWithRels` resolver in your schema.


Or even better do not store `tweetIds` in `User` collection and make such **relation with sorting & limiting**:
```js
UserTC.addRelation(
	  'tweets',
	  {
	    resolver: () => TweetTC.getResolver('findMany'),
	    prepareArgs: {
	      filter: (source) => ({ userId: source._id }),
	    },
	    projection: { _id: true },
	  }
)
```

PS> Do not forget add index `TweetSchema.index({ userId: 1 }, { background: true });` for performance.

**Comment by gHashTag** [comment]
I went according to the script, which is better

Аccording to the instructions, the model was modified:

![2017-11-15 17 07 23](https://user-images.githubusercontent.com/6774813/32840077-a228f988-ca27-11e7-9e8f-b90ec3f7b30d.png)

### Create tweet

![2017-11-15 17 28 35](https://user-images.githubusercontent.com/6774813/32841088-832b0fbe-ca2a-11e7-945b-d338257438ce.png)

### But tweets to the user were not added

![2017-11-15 17 29 58](https://user-images.githubusercontent.com/6774813/32841179-bfe1e98c-ca2a-11e7-9727-b6db75c52200.png)

### Mongoose
![2017-11-15 17 31 41](https://user-images.githubusercontent.com/6774813/32841312-02422f9e-ca2b-11e7-917d-ac9119e4d696.png)

### All [code](https://github.com/gHashTag/test-graphql-server/tree/graphql-compose-mongoose)

**Comment by gHashTag** [comment]
The northwind project implements this task.

![2017-11-15 23 05 31](https://user-images.githubusercontent.com/6774813/32858223-dc27647e-ca5b-11e7-8ccf-da2898f66d12.png)

Tried to do also, but I do not know why the array of tweets is duplicated to each user

![2017-11-15 23 22 51](https://user-images.githubusercontent.com/6774813/32858243-ef19f3c6-ca5b-11e7-8473-f3e982c9f969.png)

**Comment by nodkz** [comment]
With relations was a problem which is fixed in `graphql-compose-mongoose@1.9.6`.
It incorrectly converts ObjectId for `filter` argument. Just update package and all should work.

**Comment by gHashTag** [comment]
I guess if my questions are stupid, but for me it is important to understand how to link collections, as in my opinion this is the basis for working with the database

The first mutation created the user and got it ID

![2017-11-16 18 26 15](https://user-images.githubusercontent.com/6774813/32899306-acf1b736-cafb-11e7-8a91-282730011370.png)


The second mutation create tweet and send  userID

![2017-11-16 18 19 34](https://user-images.githubusercontent.com/6774813/32899262-87d72ff8-cafb-11e7-8acf-f91f8f800bb6.png)

but the tweetConnection is empty

![2017-11-16 18 26 15](https://user-images.githubusercontent.com/6774813/32899541-5370caa2-cafc-11e7-9b56-24d7c2b2feec.png)

at the current time the model looks like this

### UserSchema

```javascript
const UserSchema = new mongoose.Schema({
  userID: {
    type: Number,
    description: 'User unique ID',
    unique: true,
  },
  username: {
    type: String,
    unique: true
  },
  firstName: String,
  lastName: String,
  avatar: String,
  password: String,
  email: String,
}, { timestamps: true })


export const User = mongoose.model('User', UserSchema)
export const UserTC = composeWithRelay(composeWithMongoose(User))

UserTC.addRelation('tweetConnection', {
  resolver: () => TweetTC.getResolver('connection'),
  prepareArgs: {
    filter: source => ({ userID: source.userID }),
  },
  projection: { userID: true },
})
```

### TweetSchema
```javascript
const TweetSchema = new mongoose.Schema({
  tweetID: {
    type: Number,
    description: 'Tweet unique ID',
    unique: true,
  },
  text: String,
  userID: String
}, { timestamps: true })

TweetSchema.index({ userID: 1 }, { background: true })

export const Tweet = mongoose.model('Tweet', TweetSchema)
export const TweetTC = composeWithRelay(composeWithMongoose(Tweet))

TweetTC.addRelation('user', {
  resolver: () => UserTC.getResolver('findOne'),
  prepareArgs: {
    filter: source => ({ userID: source.userID }),
    skip: null,
    sort: null,
  },
  projection: { userID: true },
})
```

What's wrong?

**Comment by nodkz** [comment]
- `id` contains Relay Global Id (about purpose of this field written here https://facebook.github.io/relay/docs/graphql-object-identification.html )
- `_id` contains mongo id

So you need to use mongo id `_id` for `userID` field (not relay id).

**Comment by gHashTag** [comment]
After fix id, I see

![2017-11-16 19 03 44](https://user-images.githubusercontent.com/6774813/32903811-09123184-cb07-11e7-86ef-e54059a2dd8d.png)

The mongo necklace shows that the IDs have been added

![2017-11-16 19 56 59](https://user-images.githubusercontent.com/6774813/32904409-5a0062c2-cb08-11e7-9e99-12fb295ed8b1.png)


 ### ../model/user.js
```javascript
UserTC.addRelation(
	  'tweets',
	  {
	    resolver: () => TweetTC.getResolver('findMany'),
	    prepareArgs: {
	      filter: (source) => ({ userID: source._id }),
	    },
	    projection: { _id: true },
	  }
)
```
 ### ../model/tweet.js
```javascript
TweetTC.addRelation('user', {
  resolver: () => UserTC.getResolver('findOne'),
  prepareArgs: {
    filter: source => ({ userID: source._id }),
    skip: null,
    sort: null,
  },
  projection: { _id: true },
})
```

but fields `tweets`  is empty, why?

![2017-11-16 19 52 00](https://user-images.githubusercontent.com/6774813/32904128-ca126354-cb07-11e7-996a-f0fa4ca348c4.png)

### [All Code](https://github.com/gHashTag/test-graphql-server/tree/graphql-compose-mongoose)

**Comment by gHashTag** [comment]
Thank you very much for working example of linking collections. I filled my house with joy

for those who stalknetsya with my task, I will leave it here:

### ../models/user/js
```javascript
const UserSchema = new mongoose.Schema({
  // remove this for simplicity, cause `_id` will be crated automatically
  // userID: {
  //   type: Number,
  //   description: 'User unique ID',
  //   unique: true,
  // },
  username: {
    type: String,
    // unique: true , remove this for simplicity
  },
  firstName: String,
  lastName: String,
  password: String,
  email: {
    type: String,
    unique: true
  },
}, { timestamps: true })


export const User = mongoose.model('User', UserSchema)
export const UserTC = composeWithMongoose(User)

UserTC.addRelation(
	  'tweets',
	  {
	    resolver: () => TweetTC.getResolver('findMany'),
	    prepareArgs: {
      filter: source => ({ userID: source._id }),
	    },
	    projection: { _id: true },
	  }
)
```

### ../models/tweet.js

```javascript
const TweetSchema = new mongoose.Schema({
  // _id this field created automatically


  // remove this for simplicity
  // tweetID: {
  //   type: Number,
  //   description: 'Tweet unique ID',
  //   unique: true,  <====== this requires that all records should have unique values
  // },

  text: String,
  userID: {
    type: String,
    index: true,
  },
}, { timestamps: true })

// simle index created via model `index: true` option
// following index just allow to create complex indexes
// TweetSchema.index({ userID: 1 }, { background: true })

export const Tweet = mongoose.model('Tweet', TweetSchema)
export const TweetTC = composeWithMongoose(Tweet)

TweetTC.addRelation('user', {
  resolver: () => UserTC.getResolver('findById'),
  prepareArgs: {
    _id: source => source._id,
    skip: null,
    sort: null,
  },
  projection: { _id: true },
})
```

working!!!

![2017-11-18 11 22 11](https://user-images.githubusercontent.com/6774813/32978406-d16d5a4a-cc52-11e7-96c1-9410c1d93abb.png)

**Comment by gHashTag** [comment]
Why does this [custom resolver](https://github.com/gHashTag/test-graphql-server/blob/6196dec0aa2c812c3b901b8471043fd226f37aca/src/models/tweet.js#L31-L39) return `"user": null `?

```javascript
TweetTC.addRelation('user', {
  resolver: () => UserTC.getResolver('findById'),
  prepareArgs: {
    _id: source => source._id,
    skip: null,
    sort: null,
  },
  projection: { _id: true },
})
```

![2017-11-24 16 49 37](https://user-images.githubusercontent.com/6774813/33213158-7fc801b0-d137-11e7-9609-1bbb0c77c42e.png)

**Comment by nodkz** [comment]
Should be
```diff
- _id: source => source._id
+ _id: source => source.userID
```

**Comment by dandv** [comment]
"stalknetsya"?

**Comment by gHashTag** [comment]
@dandv  met))
