### ISSUE TITLE
Description for an Introspection Query

### ISSUE THREAD

**Issue by MDrooker** [nodkz/graphql-compose-mongoose#77]
Anyone have any thoughts of an easy way to enhance a mongoose schema to allow the population of the description field for an introspection query?

It really would be great to have that description be driven from the original mongoose schema.

Thanks
MJD

**Comment by nodkz** [comment]
Did you try this?
```js
const TweetSchema = new mongoose.Schema({
  text: {
    type: String,
    description: 'Tweet text, max length 280 characters.',
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    description: 'Author id',
  }
}, { timestamps: true } )
```

Or you mean something other?

**Comment by MDrooker** [comment]
Well now I feel stupid...thanks much.
Works like a champ.

**Comment by MDrooker** [comment]
Is there a way to add a sort ordinal field that you know of?

**Comment by nodkz** [comment]
Take a look on this
https://github.com/nodkz/graphql-compose/issues/26 or you need something else?

**Comment by MDrooker** [comment]
Not really.  We want to carry a schema attribute through(like description) so we can build our UI automated.  The order in which the fields are returned from the introspection query isnt the order we would want them to appear in our UIs.  We need a field that we can set in the mongoose schema(like description) that can is included downstream
